// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDhgXyZ0Zpbqz0JA-Rkxo79xom9OIIII',
    appId: '1:740620188822:web:2f9d7a8c4e92e435f496b7',
    messagingSenderId: '740620188822',
    projectId: 'jarvis-ai-2c009',
    authDomain: 'jarvis-ai-2c009.firebaseapp.com',
    storageBucket: 'jarvis-ai-2c009.firebasestorage.app',
    measurementId: 'G-QKHYN2ZW0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7Vukhjis8BdaEqB7uUU5RNeeJhtggc4',
    appId: '1:740620188822:android:6fead4bd45bca023f496b7',
    messagingSenderId: '740620188822',
    projectId: 'jarvis-ai-2c009',
    storageBucket: 'jarvis-ai-2c009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsrqrtyMMl3SOeWDbAGeUizGJrjxPTqAs',
    appId: '1:740620188822:ios:a9e52e413dc28e30f496b7',
    messagingSenderId: '740620188822',
    projectId: 'jarvis-ai-2c009',
    storageBucket: 'jarvis-ai-2c009.firebasestorage.app',
    iosBundleId: 'com.example.jarvisAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsrqrtyMMl3SOeWDbAGeUizGJrjxPTqAs',
    appId: '1:740620188822:ios:a9e52e413dc28e30f496b7',
    messagingSenderId: '740620188822',
    projectId: 'jarvis-ai-2c009',
    storageBucket: 'jarvis-ai-2c009.firebasestorage.app',
    iosBundleId: 'com.example.jarvisAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDhgXyZ0Zpbqz0JA-Rkxo79xom9OIIII',
    appId: '1:740620188822:web:00e3af449fe360f8f496b7',
    messagingSenderId: '740620188822',
    projectId: 'jarvis-ai-2c009',
    authDomain: 'jarvis-ai-2c009.firebaseapp.com',
    storageBucket: 'jarvis-ai-2c009.firebasestorage.app',
    measurementId: 'G-9LKSSWT8ZX',
  );
}
